name: Deploy website on push

on:
  push:
    branches:
      - main
      
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: Get latest code
    
      uses: actions/checkout@v2
      
    - name: action-yarn
      uses: comchangs/action-yarn@v0.1-beta
      
    - name: install requirements
      uses: borales/actions-yarn@v4
      with:
        cmd: install
    
    - name: build
      uses: borales/actions-yarn@v4
      with:
        cmd: run bundle

    - name: Sync files
      uses: SamKirland/FTP-Deploy_Action@4.1.10
      with:
        server: ${{secrets.FTP_SERVER}}
        username: ${{secrets.FTP_USERNAME}}
        password: ${{secrets.FTP_PASS}}
        local-dir: ./theme/
        server-dir: public_html/wp-content/themes/mazdakdev/
