name: Deploy website on push

on:
  push:
    branches:
      - main
      
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: Get the latest code 
      uses: actions/checkout@v3

    - name: setup node
      uses: actions/setup-node@v3
      with:
            node-version: 18
            
    - run: npm install
    - run: npm run bundle
    - run: npm run prod

    - name: Sync files 
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{secrets.FTP_SERVER}}
        username: ${{secrets.FTP_USER}}
        password: ${{secrets.FTP_PASS}}
        local-dir: ./theme/
        server-dir: ./wp-content/themes/mazdakdev/
